<?php

namespace shiv\contactform;

use Illuminate\Support\ServiceProvider;

class ContactFormServiceProvider extends ServiceProvider
{
    public function register()
    {
        //parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        $this->loadRoutesFrom(__DIR__.'/routes/web.php');
        $this->loadViewsFrom(__DIR__.'/resources/views/', 'contactform');
        $this->loadMigrationsFrom(__DIR__.'/Database/migrations');
    }
}
